openapi: 3.0.3
info:
  title: Swagger Bookstore - OpenAPI 3.0
  description: |
    Website backend bán sách là một ứng dụng web được sử dụng để quản lý việc bán sách. Nó có thể được sử dụng để theo dõi thông tin về sách, chẳng hạn như tiêu đề, tác giả, giá cả và số lượng có sẵn. Nó cũng có thể được sử dụng để xử lý các đơn đặt hàng và thanh toán.
  version: 1.0.11
servers:
  - url: https://nthdv-pbl6.up.railway.app/
tags:
  - name: user
    description: Everything about your users
  - name: book
    description: Everything about book
paths:
  /api/user/login:
    post:
      tags:
        - user
      summary: Login for user
      description: Login for user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: Email của người dùng
                password:
                  type: string
                  description: Mật khẩu của người dùng
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: Mã thông báo truy cập
                    default: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NDRjOTI3MDQwMTQ2YzhjOGE3N2Y1ZiIsInJvbGVJRCI6IjAiLCJpYXQiOjE2OTkwNzQxMzQsImV4cCI6MTY5OTA3NDEzNH0.lSP_L1HNaInhy4ItzyKD_AwYNoad95CxKYnOhBv40e0"
                  user:
                    type: object
                    properties:
                      _id:
                        type: string
                        description: ID của người dùng
                        default: 6544c927040146c8c8a77f5f
                      username:
                        type: string
                        description: Tên người dùng
                        default: user
                      email:
                        type: string
                        format: email
                        description: Địa chỉ email
                      password:
                        type: string
                        description: Mật khẩu
                        default: $2b$10$m9FXErML6jsWU4YZYX5eJOGiTiPHG1tt8UHsJRMlNWS9g/f78m1rK
                      roleID:
                        type: string
                        description: ID vai trò
                        default: 0
                      isVerified:
                        type: string
                        description: Xác thực người dùng
                        default: false
                      avatar:
                        type: string
                        description: Avatar người dùng
                        default: 
                      __v:
                        type: integer
                        description: Phiên bản của dữ liệu
                  status:
                    type: integer
                    description: Mã trạng thái của yêu cầu
                    default: 200
                  message:
                    type: string
                    description: Thông điệp
                    default: Login succeed!
        "400":
          description: Invalid ID 
  /api/user/register:
    post:
      tags:
        - user
      summary: Register for user
      description: Register for user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Tên của người dùng
                email:
                  type: string
                  format: email
                  description: Email của người dùng
                password:
                  type: string
                  description: Mật khẩu của người dùng
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: number
                    description: Trạng thái
                    default: 200
                  message:
                    type: string
                    description: Thông điệp
                    default: Created user succeed!
        "400":
          description: Invalid ID supplied
  /api/book:
   post:
      tags:
        - book
      summary: Login for user
      description: Login for user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Tên của người dùng
                email:
                  type: string
                  format: email
                  description: Email của người dùng
                password:
                  type: string
                  description: Mật khẩu của người dùng
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Thông điệp
                    default: Created user succeed!
        "400":
          description: Invalid ID supplied